name: Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 9.5

      - name: Setup Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: |
          npm install -g npm@^11.6
          npm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
