name: Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 9.5

      - name: Setup Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Configure pnpm
        run: |
          pnpm config set auto-install-peers true
          pnpm config set exclude-links-from-lockfile true
          npm --version
